### ISSUE TITLE
osxkeychain.h is missing

### ISSUE THREAD

**Issue by simleb** [bgentry/go-osxkeychain#1]
This looks cool, but… unless I missed something obvious, the `osxkeychain.h` file is missing.

I couldn't find it anywhere else so I assume you forgot to add it to the repo?

**Comment by md5** [comment]
Looks like this was fixed: https://github.com/bgentry/go-osxkeychain/commit/37f5f66be98de02b0d0f419f20af6272812c2681

**Comment by bgentry** [comment]
Yeah, sorry about that. If anybody is able to get farther with this project than I did, I'd love to see some contributions :) Debugging it was quite brutal as of Go 1.2 but may be a lot better now.

**Comment by md5** [comment]
No worries :+1:
