### ISSUE TITLE
Still under development?

### ISSUE THREAD

**Issue by lox** [bgentry/go-osxkeychain#5]
It looks like a fork from @gabriel / Keybase is making progress on this. I'm also looking at working on this for https://github.com/99designs/aws-vault, so I'm trying to evaluate the state of this project and @gabriel's.

Are you still interested in developing this? Should we look to consolidate effort? @gabriel, thoughts?

**Comment by bgentry** [comment]
oh nice, I was not aware of any further progress on this. I'm not actively working on the project, though I'm happy to review & merge PRs, or share commit bits if others are interested. Also happy to move it to an org if there's enough interest.

I've also still got some projects that I'd enjoy using this on, but haven't had the time to commit to getting back into the Keychain APIs.

@gabriel were you planning to make PRs or continue on the Keybase fork?

**Comment by lox** [comment]
See https://github.com/bgentry/go-osxkeychain/pull/6

**Comment by akalin** [comment]
@akalin-keybase

**Comment by akalin-keybase** [comment]
I think keybase/go-osxkeychain diverged because of GenericPassword vs. InternetPassword. If everyone is okay with #6, which looks like just turning this repo into the keybase repo, then I'm okay with it too as a starting point for common development.
