### ISSUE TITLE
Proposed API

### ISSUE THREAD

**Issue by lox** [bgentry/go-osxkeychain#7]
Some friday afternoon thoughts on what the API could look. My aim was to leave the door open to support the other types (Internet password and certificate). 

My thinking was to ditch `RemoveAndAddGenericPassword` and `FindAndRemoveGenericPassword` in favour of explicitly finding them and deleting them individually. 

Thoughts @akalin @bgentry? 

``` go
type Keychain string 

func CreateKeychain(path string, promptUser bool, password string) error {
}

// Access represents what applications have access to an item
type Access struct {
    TrustSelf bool
    TrustedApplications []string
}

// Attributes are the set of attributes that are searchable on
type Attributes struct {
    Access           Access
    CreationDate     time.Date
    ModificationDate time.Date
    Description      String
    Comment          String
    Label            String
    Account          String
    Service          String
    Generic          []String
}

func (attr *Attributes) validate() error {
}

```

**Comment by akalin-keybase** [comment]
The problem with splitting up Find and Remove is that DeleteGenericPassword will still have to do a Find, unless whatever object is returned from FindGenericPasswords includes the object ref. (Maybe it should?)

This API looks sane, but it might be a pretty big change to completely change over to it. Maybe transform the existing one into this one piece by piece? (eg., split up GenericPasswordAttributes, add parameter for keychain, etc.)

**Comment by lox** [comment]
Closing this pending some more thought and discussion.
